language: python
python:
    - "2.7"
    - "3.3"
env:
    - DJANGO_VERSION=1.4.5
    - DJANGO_VERSION=1.5.1
install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r requirements/travis.txt --use-mirrors
script:
    - "cd demo"
    - "python manage.py test radpress"

