language: python
python:
    - "2.7"
    - "3.3"
    - "3.4"
env:
    - DJANGO_VERSION=1.4.13
    - DJANGO_VERSION=1.5.8
    - DJANGO_VERSION=1.6.5
install:
    - pip install -q Django==$DJANGO_VERSION
    - pip install -r requirements/global.txt --use-mirrors
    - pip install -r requirements/travis.txt --use-mirrors
script:
    - "cd demo"
    - "python manage.py test radpress"
matrix:
  exclude:
    - python: 3.4
      env: DJANGO_VERSION=1.4.13
