language: python
python:
    - 2.7
    - 3.3
    - 3.4
env:
    - DJANGO=1.4.13
    - DJANGO=1.5.8
    - DJANGO=1.6.5
install:
    - pip install -q Django==$DJANGO
    - pip install -r requirements/global.txt --use-mirrors
    - pip install -r requirements/travis.txt --use-mirrors
script:
    - cd demo
    - python manage.py test radpress
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=1.4.13
    - python: 3.4
      env: DJANGO=1.4.13
